import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { S0, evaluate, rules } from '../model/takeWhile.ts';

const checkOnly = process.argv.includes('--check');
const root = new URL('../', import.meta.url);
const header = '> Generated by `npm run generate`. Edit the reviewed descriptors/model, not this file.\n\n';
const table = '# takeWhile — State Transition Table\n\n' + header +
  'One stable reaction per row. `T` is the next state; `G` is the ordered output word. Scope: [operator profile](../operators/takeWhile.md).\n\n' +
  '| Rule | Current state s | Input z | Guard | T(s,z) | G(s,z) |\n|---|---|---|---|---|---|\n' +
  rules.map(row => `| ${row.id} | ${row.state} | ${row.input} | ${row.guard} | ${row.T} | ${row.G} |`).join('\n') + '\n';

const edges = rules.filter(row => row.id !== 'TW08').map(row =>
  `    ${row.from} --> ${row.to}: ${row.id} ${row.input}, ${row.guard} / ${row.G}`);
const diagram = '# takeWhile — State Diagram\n\n' + header +
  'This is a **control-state projection**, not enumeration of every index. `Active` represents `Active(i)`. Edge labels are input, guard / G; target nodes represent the control component of T.\n\n' +
  '```mermaid\nstateDiagram-v2\n    [*] --> Active: S0 = Active(0)\n' + edges.join('\n') + '\n' +
  ['Completed', 'Errored', 'Cancelled'].map(kind => `    ${kind} --> ${kind}: TW08 attempted input / []`).join('\n') +
  '\n```\n\n`DisposeOwned` is a control output, not an Observable notification. The self-loops describe the model\'s settled terminal boundary; they do not claim that a disconnected source actually delivers later inputs.\n';

function belowThree(value) { return value < 3; }
function stateText(s) { return s.kind === 'Active' ? `Active(${s.index})` : s.kind; }
function wordText(word) {
  return '[' + word.map(letter => letter.kind === 'Next' ? `Next(${letter.value})` : letter.kind).join(', ') + ']';
}
let trace = '# takeWhile — Model-Predicted Trace\n\n' + header +
  'Predicate: `value < 3`; inclusive: `true`. One cold source subscription, no reentrancy, no sharing. Clock values below are illustrative virtual frames supplied by the trace, not by the operator.\n\n' +
  '| Frame t | Processing order k | State before | Input | Rule | T(s,z) | G(s,z) |\n|---|---|---|---|---|---|---|\n';
let s = S0;
for (const [k, value] of [1, 2, 3].entries()) {
  const result = evaluate(s, { kind: 'SourceNext', value }, { predicate: belowThree, inclusive: true });
  trace += `| ${1 + 2 * k} | ${k} | ${stateText(s)} | SourceNext(${value}) | ${result.ruleId} | ${stateText(result.T)} | ${wordText(result.G)} |\n`;
  s = result.T;
}
trace += '\n```text\nScheduled source:  -a-b-c-d-|    a=1, b=2, c=3, d=4\nDelivered output:  -a-b-(c|)\nSubscription:      ^----!\n```\n\nThe output 3 and completion occur in that order in frame 5. Disposal happens at the boundary. Scheduled source value 4 is not received by this closed subscription. This is a generated model prediction, not a captured RxJS execution. The matching runtime test is in [the test suite](../tests/rxjs.test.mjs).\n';

const outputs = new Map([
  ['generated/takeWhile.transitions.md', table],
  ['generated/takeWhile.visualization.md', diagram],
  ['generated/takeWhile.trace.md', trace],
]);
let failures = 0;
for (const [path, text] of outputs) {
  const destination = new URL(path, root);
  if (checkOnly) {
    let current;
    try { current = readFileSync(destination, 'utf8'); } catch { current = undefined; }
    if (current !== text) { console.error(`Stale or missing: ${path}`); failures++; }
  } else {
    writeFileSync(destination, text);
    console.log(`Generated ${fileURLToPath(destination)}`);
  }
}
if (failures) process.exitCode = 1;
else if (checkOnly) console.log('All 3 generated artifacts match the reviewed descriptors/reference model.');
