/** Render F01 additions. Existing takeWhile views remain byte-for-byte unchanged. */
import * as sw from '../model/skipWhile.ts';
import * as tk from '../model/take.ts';
import * as sk from '../model/skip.ts';
function belowFive(x) { return x < 5; }
const profiles = [
  { name: 'skipWhile', model: sw, initial: 'Skipping', p: { predicate: belowFive }, setting: 'predicate: value < 5', output: '-----c-d-|', sub: '^--------!' },
  { name: 'take', model: tk, initial: 'NotStarted', p: { count: 2 }, setting: 'count: 2', output: '-a-(b|)', sub: '^--!' },
  { name: 'skip', model: sk, initial: 'Active', p: { count: 2 }, setting: 'count: 2', output: '-----c-d-|', sub: '^--------!' },
];
function stateText(s) { return s.kind + ('index' in s ? `(${s.index})` : 'remaining' in s ? `(${s.remaining})` : ''); }
function wordText(word) { return '[' + word.map(a => a.kind === 'Next' ? `Next(${a.value})` : a.kind === 'Error' ? `Error(${a.error})` : a.kind).join(', ') + ']'; }
const header = '> Generated by `npm run generate`; edit model descriptors or the generator, not this file.\n\n';
function table(p) {
  return `# ${p.name} — State Transition Table\n\n${header}Scope: [profile](../operators/${p.name}.md). Both T and G use the same pre-input state and input.\n\n` +
    '| Rule | Current state s | Input z | Guard | T(s,z) | G(s,z) |\n|---|---|---|---|---|---|\n' +
    p.model.rules.map(r => `| ${r.id} | ${r.state} | ${r.input} | ${r.guard} | ${r.T} | ${r.G} |`).join('\n') + '\n';
}
function diagram(p) {
  const edges = p.model.rules.flatMap(r => r.from.map(from => `    ${from} --> ${r.to === 'same' ? from : r.to}: ${r.id} ${r.input}, ${r.guard} / ${r.G}`));
  return `# ${p.name} — Control-State Diagram\n\n${header}` +
    `This projects away counters; it does not enumerate all states. Arrows show input and guard / G, and the target is the control component of T. [Profile](../operators/${p.name}.md).\n\n` +
    '```mermaid\nstateDiagram-v2\n' + `    [*] --> ${p.initial}: S0\n` + edges.join('\n') + '\n```\n\n' +
    'Terminal self-loops describe attempted ordinary inputs at the settled model boundary, not delivery from a disconnected producer. SubscribeSource and DisposeOwned are resource-control letters, not Observable notifications.\n';
}
function trace(p) {
  let s = p.model.S0, k = 0;
  const rows = [];
  function receive(t, z) {
    const r = p.model.evaluate(s,z,p.p);
    rows.push(`| ${t} | ${k++} | ${stateText(s)} | ${z.kind === 'SourceNext' ? `SourceNext(${z.value})` : z.kind} | ${r.ruleId} | ${stateText(r.T)} | ${wordText(r.G)} |`);
    s = r.T;
  }
  if (p.name === 'take') receive(0,{kind:'Start'});
  for (const [i,value] of [2,4,7,1].entries()) {
    if (['Completed','Errored','Cancelled'].includes(s.kind)) break;
    receive(1+2*i,{kind:'SourceNext',value});
  }
  if (!['Completed','Errored','Cancelled'].includes(s.kind)) receive(9,{kind:'SourceComplete'});
  let text = `# ${p.name} — Model-Predicted Trace\n\n${header}Configuration: ${p.setting}. One independent cold source; no sharing or reentry. Frames come from this selected input schedule, not from the operator.\n\n` +
    '| Frame t | Order k | State before | Input z | Rule | T(s,z) | G(s,z) |\n|---|---|---|---|---|---|---|\n' + rows.join('\n') +
    `\n\n\`\`\`text\nScheduled source: -a-b-c-d-|   a=2 b=4 c=7 d=1\nOutput:           ${p.output}\nSubscription:     ${p.sub}\n\`\`\`\n\n` +
    'The subscription lane marks attachment and disconnection. Values scheduled after disconnection are not received. Disposal refers only to the owned source participation; the driver may have an independent lifetime.\n';
  if (p.name === 'take') text += '\nFor count=0, TK00 reacts to Start in frame 0 with T=Completed and G=[Complete]. The source subscription lane is empty: no SubscribeSource and no owned-source disposal.\n';
  else text += '\nSetup establishes S0 and subscribes the source before frame 1. It is a separate initializer, not an unlisted Start input.\n';
  return text + '\nThese are model predictions. Matching runtime assertions are in [the family suite](../tests/families/F01-prefix-selection.test.mjs); execution status is recorded in [evidence](../evidence/F01-prefix-selection.md).\n';
}
export function prefixViews() {
  return profiles.flatMap(p => [[`generated/${p.name}.transitions.md`,table(p)], [`generated/${p.name}.visualization.md`,diagram(p)], [`generated/${p.name}.trace.md`,trace(p)]]);
}
