/** F02 views of reviewed descriptors/reference models; preserves all F01 outputs. */
import { inspect } from 'node:util';
import * as mp from '../model/map.ts';
import * as fl from '../model/filter.ts';
import * as ig from '../model/ignoreElements.ts';
import * as mt from '../model/mapTo.ts';
import * as pl from '../model/pluck.ts';
function twiceScore(x) { return x.score * 2; }
function selected(x) { return x.score < 5; }
const profiles = [
  { name: 'map', model: mp, p: { project: twiceScore }, config: 'project: score * 2', lane: '-w-x-y-z-|', key: 'w=4 x=8 y=14 z=2' },
  { name: 'filter', model: fl, p: { predicate: selected }, config: 'predicate: score < 5', lane: '-a-b---d-|', key: 'a,b,d retain their original object references' },
  { name: 'ignoreElements', model: ig, config: 'no parameters', lane: '---------|', key: 'no Next notifications' },
  { name: 'mapTo', model: mt, p: { value: 'ready' }, config: 'constant: ready', lane: '-r-r-r-r-|', key: "r='ready'" },
  { name: 'pluck', model: pl, p: pl.configure('score'), config: "properties: ['score']", lane: '-w-x-y-z-|', key: 'w=2 x=4 y=7 z=1' },
];
const header = '> Generated by `npm run generate`; edit the model descriptors or generator, not this file.\n\n';
function valueText(value) { return inspect(value, { depth: 4, breakLength: Infinity, compact: true, colors: false }); }
function stateText(s) { return s.kind + ('index' in s ? `(${s.index})` : ''); }
function wordText(word) { return '[' + word.map(a => a.kind === 'Next' ? `Next(${valueText(a.value)})` : a.kind === 'Error' ? `Error(${valueText(a.error)})` : a.kind).join(', ') + ']'; }
function table(p) {
  return `# ${p.name} — State Transition Table\n\n${header}[Scope and source evidence](../operators/${p.name}.md). T and G refer to the same pre-input state and input.\n\n` +
    '| Rule | Current state s | Input z | Guard | T(s,z) | G(s,z) |\n|---|---|---|---|---|---|\n' +
    p.model.rules.map(r => `| ${r.id} | ${r.state} | ${r.input} | ${r.guard} | ${r.T} | ${r.G} |`).join('\n') + '\n' +
    (p.name === 'pluck' ? '\nPL-C00 is a separate construction contract: an empty property path throws before a running subscription exists. It is not an omitted transition or an Error output word.\n' : '');
}
function diagram(p) {
  const edges = p.model.rules.flatMap(r => r.from.map(from => `    ${from} --> ${r.to === 'same' ? from : r.to}: ${r.id} ${r.input}, ${r.guard} / ${r.G}`));
  return `# ${p.name} — Control-State Diagram\n\n${header}[Profile](../operators/${p.name}.md). This projects state to control phases; any retained index is omitted from the nodes. Edge labels contain the input and guard / G; the target is the control component of T.\n\n` +
    '```mermaid\nstateDiagram-v2\n    [*] --> Active: S0 after separate initialization\n' + edges.join('\n') + '\n```\n\n' +
    'DisposeOwned is a resource-control letter, not an Observable notification. Terminal self-loops describe attempted inputs at a settled boundary, not actual continued upstream delivery.\n' +
    (p.name === 'pluck' ? '\nOnly successfully constructed nonempty-path profiles reach S0. Construction failure is outside this subscription-state graph.\n' : '');
}
function trace(p) {
  let s = p.model.S0, k = 0; const rows = [];
  function input(t, z) {
    const r = p.model.evaluate(s, z, p.p);
    rows.push(`| ${t} | ${k++} | ${stateText(s)} | ${z.kind === 'SourceNext' ? `SourceNext(${valueText(z.value)})` : z.kind} | ${r.ruleId} | ${stateText(r.T)} | ${wordText(r.G)} |`);
    s = r.T;
  }
  for (const [i, score] of [2,4,7,1].entries()) input(1+2*i, { kind:'SourceNext', value:{score} });
  input(9, { kind:'SourceComplete' });
  let text = `# ${p.name} — Model-Predicted Trace\n\n${header}Configuration: ${p.config}. Independent cold source; no sharing, reentry, or operator-owned timer. The chosen source schedule supplies the virtual frames.\n\n` +
    '| Frame t | Order k | State before | Input z | Rule | T(s,z) | G(s,z) |\n|---|---|---|---|---|---|---|\n' + rows.join('\n') +
    `\n\n\`\`\`text\nSource:       -a-b-c-d-|   a={score:2} b={score:4} c={score:7} d={score:1}\nOutput:       ${p.lane}\nSubscription: ^--------!\n\`\`\`\n\nOutput key: ${p.key}. Setup initializes S0 and attaches the source before frame 1. Source completion in frame 9 produces Complete followed by owned disposal. Suppression does not disconnect the source.\n`;
  if (p.name === 'pluck') {
    text += '\nA separate input `SourceNext({})` with the same configuration uses PL02: T=Active, G=[Next(undefined)]. That is one Next notification, not silence.\n';
  }
  return text + '\nThis is a generated model prediction, not a captured runtime trace. Independently authored matching marbles are in [F02 tests](../tests/families/F02-value-selection.test.mjs); observed execution status is in [evidence](../evidence/F02-value-selection.md). Printed object contents do not establish reference identity; separate assertions do.\n';
}
export function valueViews() {
  return profiles.flatMap(p => [[`generated/${p.name}.transitions.md`,table(p)], [`generated/${p.name}.visualization.md`,diagram(p)], [`generated/${p.name}.trace.md`,trace(p)]]);
}
